---
- name: "Setup the 'ComputerName' in macOS"
  become: true
  shell: "scutil --set ComputerName {{ macos_computername.computer }}"
  when: macos_computername.computer is defined

- name: "Setup the 'LocalHostName' in macOS"
  become: true
  shell: "scutil --set LocalHostName {{ macos_computername.localhost }}"
  when: macos_computername.localhost is defined

- name: "Setup the 'HostName' in macOS"
  become: true
  shell: "scutil --set HostName {{ macos_computername.host }}"
  when: macos_computername.host is defined

- name: "Setup the network NetBIOS name"
  become: true
  osx_defaults:
    domain: "com.apple.smb.server"
    key: "NetBIOSName"
    type: "string"
    value: "{{ macos_computername.netbios }}"
    state: present
  when: macos_computername.netbios is defined